#cloud-config
package_update: true
package_upgrade: true
packages:
  - nginx
runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - echo '<h1>Welcome to nginx on Azure VM!</h1>' > /var/www/html/index.html
  - sed -i 's|root /var/www/html;|root /var/www/html;|' /etc/nginx/sites-enabled/default
  - systemctl restart nginx
