#cloud-config
packages_update: true
packages_upgrade: true
write_files:
  - path: /tmp/frr.conf
    content: |
      ip route 10.0.3.0/24 10.0.1.1
      !
      router bgp 65010
      neighbor 10.0.3.4 remote-as 65515
      neighbor 10.0.3.4 ebgp-multihop 255
      neighbor 10.0.3.5 remote-as 65515
      neighbor 10.0.3.5 ebgp-multihop 255
      !
      address-family ipv4 unicast
        neighbor 10.0.3.4 soft-reconfiguration inbound
        neighbor 10.0.3.4 route-map rmap-bogon-asns in
        neighbor 10.0.3.4 route-map rmap-azure-asns out
        neighbor 10.0.3.5 soft-reconfiguration inbound
        neighbor 10.0.3.5 route-map rmap-bogon-asns in
        neighbor 10.0.3.5 route-map rmap-azure-asns out
      exit-address-family
      exit
      !
      bgp as-path access-list azure-asns seq 5 permit _65515_
      bgp as-path access-list bogon-asns seq 5 permit _0_
      bgp as-path access-list bogon-asns seq 10 permit _23456_
      bgp as-path access-list bogon-asns seq 15 permit _1310[0-6][0-9]_|_13107[0-1]_
      bgp as-path access-list bogon-asns seq 20 deny _65515_
      bgp as-path access-list bogon-asns seq 25 permit ^65
      !
      route-map rmap-bogon-asns deny 5
      match as-path bogon-asns
      exit
      !
      route-map rmap-bogon-asns permit 10
      exit
      !
      route-map rmap-azure-asns deny 5
      match as-path azure-asns
      exit
      !
      route-map rmap-azure-asns permit 10
      exit
      !
runcmd:
  # enable IP forwarding
  - sudo sed -i.org 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
  - sudo sysctl -p
  # install FRRouting
  - curl -s https://deb.frrouting.org/frr/keys.asc | gpg --no-default-keyring --keyring /tmp/frrouting-keyring.gpg --import
  - gpg --no-default-keyring --keyring /tmp/frrouting-keyring.gpg --export --output /usr/share/keyrings/frrouting-keyring.gpg
  - FRRVER="frr-stable"
  - echo deb [signed-by=/usr/share/keyrings/frrouting-keyring.gpg] https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER | tee -a /etc/apt/sources.list.d/frr.list
  - sudo apt update && apt -y install frr frr-pythontools
  - sudo sed -i.org 's/bgpd=no/bgpd=yes/' /etc/frr/daemons
  - sudo cp /tmp/frr.conf /etc/frr/frr.conf
  - sudo systemctl restart frr